import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/FSKyE8Py14L
 */
import { Link } from "@remix-run/react";
import {
	IconBraces,
	IconHome,
	IconMoon,
	IconPackage,
	IconSearch,
	IconSun,
	IconTable,
	IconUser,
} from "@tabler/icons-react";
import React from "react";
import { useAtom } from "jotai";
import { Image } from "lucide-react";
import { darkModeAtom } from "~/models/local";

export function IndexPage({ children }: { children: React.ReactNode }) {
	const [isDarkMode, setDarkMode] = useAtom(darkModeAtom);

	return (
		<div className="h-screen flex flex-col w-full">
			<header className="flex h-16 gap-1 items-center border-b bg-gray-100/50 dark:bg-gray-800/50 backdrop-blur-sm px-4 md:px-6">
				<div className="flex items-center gap-4 lg:gap-8">
					<Link
						className="flex items-center gap-2 text-lg font-semibold"
						to="/"
					>
						<IconPackage className="h-6 w-6" />
						<span>SPA!</span>
					</Link>
				</div>
				<div className="flex-1 min-w-0 w-full mx-4 md:mx-6">
					<form className="w-full">
						<div className="relative">
							<IconSearch className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-300 dark:text-gray-700" />
							<Input
								className="bg-white w-full pl-8"
								placeholder="特徴から探す"
								type="search"
							/>
						</div>
					</form>
				</div>
				<div className="flex items-center gap-3">
					<Button
						className="rounded-full"
						size="icon"
						variant="ghost"
						onClick={() => setDarkMode((mode) => !mode)}
					>
						{!isDarkMode ? <IconSun size={18} /> : <IconMoon size={18} />}
					</Button>
					<Button className="rounded-full" size="icon" variant="ghost">
						<IconUser size={18} />
						<span className="sr-only">View profile</span>
					</Button>
				</div>
			</header>
			<div className="flex flex-1 overflow-hidden">
				<div className="hidden pr-4 md:flex flex-col border-r bg-gray-100/40 dark:bg-gray-800/40">
					<div className="border-b">
						<nav className="flex flex-col gap-1">
							<Link
								className="flex w-full items-center gap-2 px-4 py-2 text-sm font-medium"
								to="/"
							>
								<IconHome className="w-5" />
								トップページ
							</Link>
							<Link
								className="flex w-full items-center gap-2 px-4 py-2 text-sm font-medium"
								to="/from-list"
							>
								<IconTable className="w-5" />
								一覧から探す
							</Link>
							<Link
								className="flex w-full items-center gap-2 px-4 py-2 text-sm font-medium"
								to="/from-images"
							>
								<Image className="w-5" />
								画像から探す
							</Link>
							<Link
								className="flex w-full items-center gap-2 px-4 py-2 text-sm font-medium"
								to="/debug"
							>
								<IconBraces className="w-5" />
								DEBUG
							</Link>
						</nav>
					</div>
					<div className="flex-1 border-b border-t" />
					<div className="flex grid place-items-center">
						<Link
							className="flex items-center gap-2 px-4 py-2 text-lg font-semibold"
							to="/"
						>
							<IconPackage className="h-6 w-6" />
							<span>SPA!</span>
						</Link>
					</div>
				</div>
				<main className="flex-1 flex flex-col min-h-0 w-full overflow-auto">
					{children}
				</main>
			</div>
		</div>
	);
}
