name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  # build-and-deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4

  #   - name: Use Node.js
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: '20'

  #   - name: Cache npm install and build
  #     uses: actions/cache@v3
  #     with:
  #       path: ~/.npm
  #       key: ${{ runner.os }}-node-${{ hashFiles('**/client/package-lock.json') }}
  #       restore-keys: ${{ runner.os }}-npm-

  #   - name: Install Dependencies
  #     run: npm ci

  #   - name: Build
  #     run: npm run build

  #   - name: Deploy to GitHub Pages
  #     uses: peaceiris/actions-gh-pages@v3
  #     with:
  #       github_token: ${{ secrets.GITHUB_TOKEN }}
  #       publish_dir: ./build/client

  build-devcontainer:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          # Change this to be your CI task/script
          runCmd: echo hello
